controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.user.create:
    path: /api/category
    controller: App\Controller\CreateCategoryAction
    methods: [ POST ]
