controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.user.create:
    path: /api/category/create
    controller: App\Controller\CreateCategoryAction
    methods: [ POST ]

app.user.update:
    path: /api/category/update
    controller: App\Controller\UpdateCategoryAction
    methods: [ POST ]
