version: '3.8'

services:
  portfolio_backend:
    container_name: portfolio_backend
    build:
      context: ./docker
      args:
        UID: $U_ID
    restart: unless-stopped
    volumes:
      - ./:/var/www:delegated
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=Portfolio
    ports:
      - '6060:8000'
    networks:
      - portfolio_network
    depends_on:
      - postgres_database
#    command: symfony serve --dir=apps/frontend/frontend/public --port=9090

  portfolio_backoffice_front:
    container_name: portfolio_backoffice_front
    build:
      context: ./docker
      args:
        UID: $U_ID
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - portfolio_backend
    networks:
      - portfolio_network

  portfolio_front:
    container_name: portfolio_front
    build:
      context: ./docker
      args:
        UID: $U_ID
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - portfolio_backend
    networks:
      - portfolio_network

#  portfolio_backend_mysql:
#    container_name: portfolio_backend_mysql
#    image: mysql:8.0.26
#    ports:
#      - '3336:3306'
#    environment:
#      MYSQL_DATABASE: portfolio
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - portfolio_backend_mysql_data:/var/lib/mysql
##    healthcheck:
##      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
##      interval: 2s
##      timeout: 10s
##      retries: 10
#    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
#    networks:
#      - portfolio_network

  postgres_database:
    container_name: postgres_database
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
      # You should definitely change the password in production
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    networks:
      - portfolio_network
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

networks:
  portfolio_network:

volumes:
#  portfolio_backend_mysql_data:
  database_data:
